# Generated by Django 4.0.1 on 2022-03-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiletable',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='profiletable',
            name='image',
        ),
        migrations.AlterField(
            model_name='profiletable',
            name='url_img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img_profile/'),
        ),
    ]
