# Generated by Django 4.0.1 on 2022-03-07 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiletable',
            old_name='user_id',
            new_name='userIdentificador',
        ),
    ]
