# Generated by Django 4.0.1 on 2022-03-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_rename_user_id_profiletable_useridentificador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiletable',
            old_name='userIdentificador',
            new_name='user',
        ),
    ]
