# Generated by Django 4.0.1 on 2022-03-07 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_rename_useridentificador_profiletable_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiletable',
            name='created',
        ),
        migrations.RemoveField(
            model_name='profiletable',
            name='edited',
        ),
    ]
