# Generated by Django 4.0.1 on 2022-01-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerComponente', '0002_rename_edit_primertabla_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primertabla',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
